development:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye/faye"
  secret_token: "f084df2f608bf945a3a9824f6ea93cded1d3b57e8edb6c52e9bcf782776f9542"
  signature_expiration: 3600 # one hour
